# Generated by Django 5.0.3 on 2025-11-25 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Document de contrat'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de contrat'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('INTERNSHIP', 'Stage'), ('FREELANCE', 'Freelance'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='diploma',
            field=models.CharField(blank=True, max_length=255, verbose_name='Diplômes principaux'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('HIGH_SCHOOL', 'Bac ou moins'), ('BACHELOR', 'Licence / Bachelor'), ('MASTER', 'Master'), ('DOCTORATE', 'Doctorat'), ('OTHER', 'Autre')], max_length=20, verbose_name="Niveau d'études"),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], max_length=1, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_employee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire (brut / net)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter / X'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Années d'expérience"),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio / Notes internes'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Poste occupé / recherché'),
        ),
    ]
