# Generated by Django 5.0.3 on 2026-09-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Structure / entreprise')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('subject', models.CharField(choices=[('QUOTE', 'Demande de devis'), ('STUDIO', 'Location de studio'), ('LIVE', 'Live streaming / captation'), ('EQUIPMENT', 'Location de matériel'), ('TRAINING', 'Formation'), ('PARTNERSHIP', 'Partenariat'), ('OTHER', 'Autre demande')], default='QUOTE', max_length=20, verbose_name='Objet')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='Budget indicatif')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('NEW', 'Nouvelle'), ('IN_PROGRESS', 'En cours de traitement'), ('DONE', 'Traitée')], default='NEW', max_length=20, verbose_name='Statut')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçue le')),
            ],
            options={
                'verbose_name': 'Demande de contact',
                'verbose_name_plural': 'Demandes de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
