# Generated by Django 5.0.3 on 2026-02-06 11:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_priority', models.BooleanField(default=False, help_text='Zone prioritaire (Bobo, Koudougou, etc.)')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Région',
                'ordering': ['-is_priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_code', models.CharField(help_text='Ex: BF-BOBO-001', max_length=20, unique=True, verbose_name='Code partenaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('suspension_reason', models.TextField(blank=True, verbose_name='Raison suspension')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de commission (%)')),
                ('total_contracts', models.IntegerField(default=0, verbose_name='Contrats apportés')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='CA généré (FCFA)')),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Commission totale (FCFA)')),
                ('total_commission_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Commission versée (FCFA)')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('last_contract_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_partner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Partenaire d'affaires",
                'verbose_name_plural': "Partenaires d'affaires",
                'ordering': ['-total_revenue'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_type', models.CharField(choices=[('institution', 'Institution'), ('ong', 'ONG'), ('company', 'Entreprise'), ('individual', 'Particulier'), ('event', 'Organisateur événement')], max_length=50, verbose_name='Type de client')),
                ('client_contact', models.CharField(max_length=200, verbose_name='Contact client')),
                ('service_type', models.CharField(help_text='Ex: Live streaming, Production vidéo, Formation...', max_length=100, verbose_name='Type de service')),
                ('description', models.TextField(verbose_name='Description du projet')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant du contrat (FCFA)')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de commission appliqué (%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Montant de la commission (FCFA)')),
                ('contract_file', models.FileField(blank=True, upload_to='partners/contracts/', verbose_name='Contrat signé')),
                ('status', models.CharField(choices=[('draft', '📝 Brouillon'), ('pending', '⏳ En attente validation'), ('validated', '✅ Validé'), ('signed', '🖊️ Signé'), ('in_progress', '🔄 En cours'), ('completed', '✔️ Terminé'), ('cancelled', '❌ Annulé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='business_partners.businesspartner')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant versé (FCFA)')),
                ('payment_method', models.CharField(choices=[('orange_money', 'Orange Money'), ('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('cash', 'Espèces')], max_length=20, verbose_name='Méthode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement')),
                ('receipt', models.FileField(blank=True, upload_to='partners/payments/', verbose_name='Reçu/Preuve')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='business_partners.businesspartner')),
                ('contracts', models.ManyToManyField(help_text='Contrats pour lesquels cette commission est versée', related_name='commission_payments', to='business_partners.contract')),
            ],
            options={
                'verbose_name': 'Paiement de commission',
                'verbose_name_plural': 'Paiements de commissions',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('id_type', models.CharField(choices=[('cnib', 'CNIB'), ('passport', 'Passeport')], default='cnib', max_length=20, verbose_name='Type de pièce')),
                ('id_number', models.CharField(max_length=50, verbose_name='Numéro de pièce')),
                ('id_document', models.FileField(blank=True, upload_to='partners/documents/', verbose_name='Copie de la pièce')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('current_activity', models.CharField(help_text='Ex: Entrepreneur, Commercial, Journaliste...', max_length=200, verbose_name='Activité actuelle')),
                ('experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name="Années d'expérience")),
                ('network_strength', models.CharField(choices=[('weak', 'Limité'), ('medium', 'Moyen'), ('strong', 'Fort'), ('very_strong', 'Très fort')], default='medium', max_length=20, verbose_name='Force du réseau')),
                ('network_description', models.TextField(help_text="Institutions, entreprises, secteurs d'activité que vous connaissez", verbose_name='Description du réseau')),
                ('sectors_knowledge', models.TextField(help_text='Ex: Événementiel, ONG, Corporate, Médias...', verbose_name='Secteurs de compétence')),
                ('why_oloustream', models.TextField(help_text='Motivations pour ce partenariat', verbose_name='Pourquoi Oloustream ?')),
                ('availability', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('flexible', 'Flexible')], default='flexible', max_length=20, verbose_name='Disponibilité')),
                ('references', models.TextField(blank=True, help_text='Noms et contacts de personnes pouvant attester de votre sérieux', verbose_name='Références')),
                ('status', models.CharField(choices=[('pending', '⏳ En attente'), ('reviewing', "🔍 En cours d'examen"), ('interview', '📞 Entretien planifié'), ('approved', '✅ Approuvée'), ('rejected', '❌ Rejetée')], default='pending', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text="Réservé à l'équipe Oloustream", verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_partners.region', verbose_name='Ville/Région')),
            ],
            options={
                'verbose_name': 'Candidature partenaire',
                'verbose_name_plural': 'Candidatures partenaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to='business_partners.partnerapplication'),
        ),
    ]
