# Generated by Django 5.0.3 on 2026-09-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('validated', 'Validé'), ('signed', 'Signé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('interview', 'Entretien planifié'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20),
        ),
    ]
