# Generated by Django 5.0.3 on 2025-11-26 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_offerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icône (classe CSS Phosphor ou autre)')),
            ],
            options={
                'verbose_name': 'Catégorie de service',
                'verbose_name_plural': 'Catégories de services',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='difficulty_level',
            field=models.CharField(choices=[('BASIC', 'Basique'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('CUSTOM', 'Sur-mesure')], default='STANDARD', max_length=20, verbose_name='Niveau de complexité'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_max_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée maximale (minutes)'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_min_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée minimale (minutes)'),
        ),
        migrations.AddField(
            model_name='service',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='Notes internes (non visibles pour le client)'),
        ),
        migrations.AddField(
            model_name='service',
            name='location_type',
            field=models.CharField(choices=[('ONSITE', 'Sur site (client)'), ('STUDIO', 'En studio'), ('REMOTE', 'À distance'), ('HYBRID', 'Hybride')], default='STUDIO', max_length=20, verbose_name='Lieu de prestation'),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_equipment_rental',
            field=models.BooleanField(default=False, verbose_name='Nécessite de la location matériel'),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_studio',
            field=models.BooleanField(default=False, verbose_name='Nécessite un studio'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('LIVE_STREAMING', 'Live streaming'), ('PRODUCTION', 'Production audiovisuelle'), ('POST_PROD', 'Post-production'), ('RENTAL', 'Location matériel'), ('TRAINING', 'Formation'), ('CONSULTING', 'Conseil'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Type de service'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description courte'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de base (F CFA)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Description détaillée'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services_app.servicecategory', verbose_name='Catégorie'),
        ),
    ]
