# Generated by Django 5.0.3 on 2025-11-26 11:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0003_servicecategory_alter_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la catégorie de formation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icône (classe CSS)')),
            ],
            options={
                'verbose_name': 'Catégorie de formation',
                'verbose_name_plural': 'Catégories de formation',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['title'], 'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AddField(
            model_name='training',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='training_brochures/', verbose_name='Brochure PDF'),
        ),
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créée le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='training',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainings/', verbose_name='Image / visuel'),
        ),
        migrations.AddField(
            model_name='training',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Débutant'), ('INTERMEDIATE', 'Intermédiaire'), ('ADVANCED', 'Avancé'), ('ALL_LEVELS', 'Tous niveaux')], default='ALL_LEVELS', max_length=20, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='training',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lieu (si présentiel)'),
        ),
        migrations.AddField(
            model_name='training',
            name='max_seats',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre maximum de participants'),
        ),
        migrations.AddField(
            model_name='training',
            name='mode',
            field=models.CharField(choices=[('ONSITE', 'Présentiel'), ('ONLINE', 'En ligne'), ('HYBRID', 'Hybride')], default='ONSITE', max_length=20, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='training',
            name='objectives',
            field=models.TextField(blank=True, verbose_name='Objectifs pédagogiques'),
        ),
        migrations.AddField(
            model_name='training',
            name='prerequisites',
            field=models.TextField(blank=True, verbose_name='Prérequis'),
        ),
        migrations.AddField(
            model_name='training',
            name='program',
            field=models.TextField(blank=True, verbose_name='Programme détaillé / modules'),
        ),
        migrations.AddField(
            model_name='training',
            name='schedule',
            field=models.TextField(blank=True, verbose_name='Horaires / planning (ex : week-ends, soirs)'),
        ),
        migrations.AddField(
            model_name='training',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description courte'),
        ),
        migrations.AddField(
            model_name='training',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='training',
            name='target_audience',
            field=models.TextField(blank=True, verbose_name='Public cible'),
        ),
        migrations.AddField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mise à jour le'),
        ),
        migrations.AlterField(
            model_name='training',
            name='certification',
            field=models.BooleanField(default=False, verbose_name='Certification délivrée'),
        ),
        migrations.AlterField(
            model_name='training',
            name='description',
            field=models.TextField(verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='training',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée totale (heures)'),
        ),
        migrations.AlterField(
            model_name='training',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix (F CFA)'),
        ),
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='services_app.trainingcategory', verbose_name='Catégorie'),
        ),
    ]
