# Generated by Django 5.0.3 on 2025-11-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0004_trainingcategory_alter_training_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'Partenaire', 'verbose_name_plural': 'Partenaires'},
        ),
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Contact principal'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone de contact'),
        ),
        migrations.AddField(
            model_name='partner',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partnership_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('SUPPLIER', 'Fournisseur'), ('SPONSOR', 'Sponsor'), ('MEDIA', 'Partenaire média'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Type de partenariat'),
        ),
    ]
