# Generated by Django 5.0.3 on 2026-01-07 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0005_alter_partner_options_partner_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('CLOSED', 'Fermé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('offer_type', models.CharField(choices=[('INTERNSHIP', 'Stage'), ('JOB', 'Emploi')], default='JOB', max_length=20, verbose_name="Type d'offre")),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Département / Pôle')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Lieu')),
                ('contract_type', models.CharField(blank=True, max_length=120, verbose_name='Type de contrat')),
                ('level', models.CharField(blank=True, max_length=120, verbose_name='Niveau')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Résumé')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Missions')),
                ('requirements', models.TextField(blank=True, verbose_name='Profil recherché')),
                ('benefits', models.TextField(blank=True, verbose_name='Avantages')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Offre (Recrutement)',
                'verbose_name_plural': 'Offres (Recrutement)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('cv', models.FileField(upload_to='job_applications/cv/', verbose_name='CV (PDF)')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Message / lettre')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio / LinkedIn')),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('REVIEWING', 'En cours'), ('SHORTLISTED', 'Présélectionné'), ('REJECTED', 'Refusé'), ('HIRED', 'Recruté')], default='NEW', max_length=20, verbose_name='Statut')),
                ('internal_note', models.TextField(blank=True, verbose_name='Note interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Candidature le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='services_app.joboffer', verbose_name='Offre')),
            ],
            options={
                'verbose_name': 'Candidature (Recrutement)',
                'verbose_name_plural': 'Candidatures (Recrutement)',
                'ordering': ['-created_at'],
                'unique_together': {('offer', 'user')},
            },
        ),
    ]
