# Generated by Django 5.0.3 on 2026-01-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0006_joboffer_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='job_offers/posters/', verbose_name='Affiche / visuel'),
        ),
    ]
