# Generated by Django 5.0.3 on 2026-01-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0007_joboffer_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('FREELANCE', 'Freelance'), ('STAGE', 'Stage')], default='', max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='level',
            field=models.CharField(blank=True, choices=[('BAC', 'BAC'), ('BAC+1', 'BAC+1'), ('BAC+2', 'BAC+2'), ('BAC+3', 'BAC+3'), ('BAC+4', 'BAC+4'), ('BAC+5', 'BAC+5')], default='', max_length=20, verbose_name='Niveau minimum'),
        ),
    ]
