# Generated by Django 5.0.3 on 2025-11-25 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'Équipement', 'verbose_name_plural': 'Équipements'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='accessories_included',
            field=models.TextField(blank=True, verbose_name='Accessoires inclus (câbles, batteries, etc.)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_equipments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur actuel'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='important_notes',
            field=models.TextField(blank=True, verbose_name='Notes importantes'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=150, verbose_name='Emplacement physique'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_notes',
            field=models.TextField(blank=True, verbose_name='Notes de maintenance (réparations, problèmes)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manual',
            field=models.FileField(blank=True, null=True, upload_to='equipment_manuals/', verbose_name="Manuel d'utilisation (PDF)"),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modèle'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_photos/', verbose_name="Photo de l'équipement"),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix d'achat"),
        ),
        migrations.AddField(
            model_name='equipment',
            name='technical_specs',
            field=models.TextField(blank=True, verbose_name='Spécifications techniques (poids, dimensions, puissance, etc.)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='studio.equipmentcategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numéro de série'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('IN_USE', 'En utilisation'), ('MAINTENANCE', 'En maintenance'), ('OUT_OF_SERVICE', 'Hors service'), ('RETIRED', 'Retiré')], default='AVAILABLE', max_length=20, verbose_name='Statut'),
        ),
    ]
