# Generated by Django 5.0.3 on 2025-11-25 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_equipment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('REJECTED', 'Refusée'), ('CANCELLED', 'Annulée'), ('COMPLETED', 'Terminée')], max_length=20, verbose_name='Ancien statut')),
                ('new_status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('REJECTED', 'Refusée'), ('CANCELLED', 'Annulée'), ('COMPLETED', 'Terminée')], max_length=20, verbose_name='Nouveau statut')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Modifié le')),
                ('note', models.TextField(blank=True, verbose_name='Note / commentaire')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='studio.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Historique de statut de réservation',
                'verbose_name_plural': 'Historiques de statut de réservation',
                'ordering': ['-changed_at'],
            },
        ),
    ]
