# Generated by Django 5.0.3 on 2025-12-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_reservationstatushistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['name'], 'verbose_name': 'Studio', 'verbose_name_plural': 'Studios'},
        ),
        migrations.RemoveField(
            model_name='studio',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='location',
        ),
        migrations.AddField(
            model_name='studio',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='studio',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si laissé vide, sera calculé automatiquement (longueur x largeur).', max_digits=8, null=True, verbose_name='Superficie (m²)'),
        ),
        migrations.AddField(
            model_name='studio',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité maximale (nombre de personnes)'),
        ),
        migrations.AddField(
            model_name='studio',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='studio',
            name='code',
            field=models.CharField(blank=True, help_text="Code interne (optionnel), utile pour l'administration.", max_length=50, verbose_name='Code du studio'),
        ),
        migrations.AddField(
            model_name='studio',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='studio',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Réduction / promotion (%)'),
        ),
        migrations.AddField(
            model_name='studio',
            name='equip_accessories',
            field=models.TextField(blank=True, verbose_name='Accessoires'),
        ),
        migrations.AddField(
            model_name='studio',
            name='equip_cameras',
            field=models.TextField(blank=True, verbose_name='Caméras présentes'),
        ),
        migrations.AddField(
            model_name='studio',
            name='equip_control_room',
            field=models.TextField(blank=True, verbose_name='Régie'),
        ),
        migrations.AddField(
            model_name='studio',
            name='equip_lights',
            field=models.TextField(blank=True, verbose_name='Lumières'),
        ),
        migrations.AddField(
            model_name='studio',
            name='equip_microphones',
            field=models.TextField(blank=True, verbose_name='Micros disponibles'),
        ),
        migrations.AddField(
            model_name='studio',
            name='equip_screens',
            field=models.TextField(blank=True, verbose_name='Écrans'),
        ),
        migrations.AddField(
            model_name='studio',
            name='extra_options',
            field=models.TextField(blank=True, help_text='Exemple : Fondu décor, enregistrement multi‑cam, etc.', verbose_name='Options supplémentaires (liste)'),
        ),
        migrations.AddField(
            model_name='studio',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Hauteur (m)'),
        ),
        migrations.AddField(
            model_name='studio',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Longueur (m)'),
        ),
        migrations.AddField(
            model_name='studio',
            name='lighting_included',
            field=models.BooleanField(default=False, help_text="Cochez si le studio est équipé d'un éclairage intégré.", verbose_name='Éclairage intégré'),
        ),
        migrations.AddField(
            model_name='studio',
            name='lighting_type',
            field=models.TextField(blank=True, verbose_name='Type de lumières (LED, projecteurs, softbox…)'),
        ),
        migrations.AddField(
            model_name='studio',
            name='opening_days',
            field=models.CharField(blank=True, help_text='Exemple : Lundi au samedi', max_length=100, verbose_name="Jours d'ouverture"),
        ),
        migrations.AddField(
            model_name='studio',
            name='opening_hours',
            field=models.CharField(blank=True, help_text='Exemple : 08h00 - 20h00', max_length=100, verbose_name="Heures d'ouverture"),
        ),
        migrations.AddField(
            model_name='studio',
            name='price_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix par journée (FCFA)'),
        ),
        migrations.AddField(
            model_name='studio',
            name='price_half_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix par demi-journée (FCFA)'),
        ),
        migrations.AddField(
            model_name='studio',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix par heure (FCFA)'),
        ),
        migrations.AddField(
            model_name='studio',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'Indisponible'), ('MAINTENANCE', 'En maintenance')], default='AVAILABLE', max_length=20, verbose_name='Statut du studio'),
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_type',
            field=models.CharField(choices=[('VIDEO', 'Studio vidéo'), ('AUDIO', 'Studio audio / podcast'), ('PHOTO', 'Studio photo'), ('MULTI', 'Multi-usage')], default='MULTI', max_length=20, verbose_name='Type de studio'),
        ),
        migrations.AddField(
            model_name='studio',
            name='technicians_required',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de techniciens requis'),
        ),
        migrations.AddField(
            model_name='studio',
            name='unavailable_dates',
            field=models.TextField(blank=True, help_text='Exemple : 25/12, 01/01, etc. (ou note libre)', verbose_name='Dates indisponibles'),
        ),
        migrations.AddField(
            model_name='studio',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Largeur (m)'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si décoché, le studio sera masqué côté utilisateur.', verbose_name='Actif'),
        ),
    ]
