# Generated by Django 5.0.3 on 2025-12-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_studio_options_remove_studio_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='studios/', verbose_name='Image principale du studio'),
        ),
    ]
