# Generated by Django 5.0.3 on 2026-01-16 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0008_alter_jobapplication_status_and_more'),
        ('studio', '0005_studio_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='budget_known',
            field=models.BooleanField(default=False, verbose_name='Le client a une idée de son budget'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget maximum (FCFA)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget minimum (FCFA)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='budget_notes',
            field=models.TextField(blank=True, help_text="Par ex. 'Je souhaite être conseillé'.", verbose_name='Commentaires sur le budget'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_additional_message',
            field=models.TextField(blank=True, verbose_name='Message complémentaire du client'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_company',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom de la structure / marque'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_full_name',
            field=models.CharField(blank=True, help_text='Nom de la personne à contacter pour ce projet.', max_length=150, verbose_name='Nom & Prénom'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_pref_call',
            field=models.BooleanField(default=False, verbose_name='Souhaite être rappelé par un conseiller technique'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_pref_email_quote',
            field=models.BooleanField(default=False, verbose_name='Préfère recevoir un devis détaillé par email'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_pref_meeting',
            field=models.BooleanField(default=False, verbose_name='Souhaite prendre rendez-vous pour en discuter'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='delivery_deadline',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('URGENT', 'Urgent'), ('TO_DISCUSS', 'À discuter')], max_length=20, verbose_name='Délai de livraison souhaité'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='episode_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Exemples : 3, 7, 13, 26…', null=True, verbose_name='Durée moyenne par épisode (en minutes)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='episodes_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'épisodes à tourner"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='episodes_notes',
            field=models.CharField(blank=True, help_text="À utiliser si '2 à 5', '6 à 10' ou 'plus'.", max_length=255, verbose_name="Précisions sur le nombre d'épisodes"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='format_type',
            field=models.CharField(blank=True, choices=[('MONOLOGUE', 'Monologue (1 intervenant)'), ('INTERVIEW', 'Entretien / interview'), ('TALK_SHOW', 'Talk-show / débat'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type de format'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='option_custom_set',
            field=models.BooleanField(default=False, verbose_name='Studio + décor personnalisé'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='option_express_delivery',
            field=models.BooleanField(default=False, verbose_name='Livraison express souhaitée'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='option_make_up',
            field=models.BooleanField(default=False, verbose_name='Studio + décor + maquilleuse professionnelle'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='option_technical_team',
            field=models.BooleanField(default=False, verbose_name='Équipe technique (cadrage, son, lumière)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='option_video_editing',
            field=models.BooleanField(default=False, verbose_name='Besoin de montage vidéo'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='participants_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre total d'intervenants sur le plateau"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='participants_details',
            field=models.CharField(blank=True, help_text='À préciser si plus de 4 intervenants ou configuration spéciale.', max_length=255, verbose_name='Détails sur les intervenants'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='preferred_date_1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='1ère date souhaitée'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='preferred_date_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='2ᵉ date souhaitée'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='preferred_period',
            field=models.CharField(blank=True, choices=[('WEEKDAY', 'En semaine'), ('WEEKEND', 'Week-end'), ('FLEXIBLE', 'À définir / flexible')], max_length=20, verbose_name='Période préférée'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='project_references',
            field=models.TextField(blank=True, help_text='Liens YouTube, Instagram, émissions, podcasts, etc.', verbose_name='Exemples / références qui vous inspirent'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='project_summary',
            field=models.TextField(blank=True, help_text='Objectif, cible, type de contenu…', verbose_name='Résumé du projet vidéo'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rental_studio_only',
            field=models.BooleanField(default=False, verbose_name='Location du studio uniquement'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='scheduling_notes',
            field=models.TextField(blank=True, help_text="Contraintes d'horaires, plage horaire idéale, etc.", verbose_name='Notes sur la planification'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='specific_constraints',
            field=models.TextField(blank=True, help_text='Lancement, événement, diffusion à date précise, etc.', verbose_name='Contraintes particulières'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='support_other_details',
            field=models.TextField(blank=True, verbose_name="Précisions complémentaires sur l'accompagnement"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='studio.equipment', verbose_name='Équipements'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='services_app.service', verbose_name='Service associé'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.studio', verbose_name='Studio'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
